# Generated by Django 3.0.7 on 2020-06-16 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=1000)),
                ('belief', models.CharField(max_length=1000)),
                ('target', models.CharField(max_length=1000)),
                ('strength', models.CharField(max_length=1000)),
                ('valuation', models.CharField(max_length=1000)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.Entry')),
            ],
        ),
    ]
