# Generated by Django 3.0.7 on 2020-06-17 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0003_extraction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extraction',
            old_name='ext_text',
            new_name='sub_text',
        ),
        migrations.AddField(
            model_name='extraction',
            name='pred_text',
            field=models.CharField(default='defualt', max_length=1000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ExtArguments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arg_text', models.CharField(max_length=1000)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.Extraction')),
            ],
        ),
    ]
