# Generated by Django 3.0.7 on 2020-06-17 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0004_auto_20200617_2031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExtArguments',
            new_name='ExtArgument',
        ),
    ]
