# Generated by Django 3.0.7 on 2020-06-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0005_auto_20200617_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='eID',
            field=models.IntegerField(default=1),
        ),
    ]
