# Generated by Django 3.0.7 on 2020-06-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0006_entry_eid'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='editing',
            field=models.BooleanField(default=False),
        ),
    ]
