# Generated by Django 3.0.7 on 2020-06-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0008_remove_annotation_editing'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
