# Generated by Django 3.0.7 on 2020-07-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0010_auto_20200705_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='strength',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='valuation',
            field=models.IntegerField(),
        ),
    ]
